// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnBZKzLnEqtscHk6iSYMKoJzSZESGl7hs',
    appId: '1:26205765854:web:024866135c83f36bd7024f',
    messagingSenderId: '26205765854',
    projectId: 'fir-learn-83839',
    authDomain: 'fir-learn-83839.firebaseapp.com',
    storageBucket: 'fir-learn-83839.appspot.com',
    measurementId: 'G-43EXFVNYJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3bsj6ip04fuDRMH8cu7I8u5bgN6eFjWE',
    appId: '1:26205765854:android:3d6bb5de34ca7a94d7024f',
    messagingSenderId: '26205765854',
    projectId: 'fir-learn-83839',
    storageBucket: 'fir-learn-83839.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbpBsFr1zvqDcvrrqMSfvRecOAuCT-540',
    appId: '1:26205765854:ios:0e5ff70f555d789ad7024f',
    messagingSenderId: '26205765854',
    projectId: 'fir-learn-83839',
    storageBucket: 'fir-learn-83839.appspot.com',
    androidClientId: '26205765854-9udtdd8acn4ljgi32vmmi8tfdeala3io.apps.googleusercontent.com',
    iosClientId: '26205765854-d22tt924dul4jhgr2q2jt9ccu862rlfs.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbpBsFr1zvqDcvrrqMSfvRecOAuCT-540',
    appId: '1:26205765854:ios:a3da192478200e8fd7024f',
    messagingSenderId: '26205765854',
    projectId: 'fir-learn-83839',
    storageBucket: 'fir-learn-83839.appspot.com',
    androidClientId: '26205765854-9udtdd8acn4ljgi32vmmi8tfdeala3io.apps.googleusercontent.com',
    iosClientId: '26205765854-ln75i73c53ip07nvb6u00a5826uqv9qt.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
